export const wordList = [
  // Ingredients
  "honey",
  "water",
  "yeast",
  "fruit",
  "spices",
  "herbs",
  "tannin",
  "nutrients",
  "adjunct",
  "malt",
  "hops",
  "sugar",
  "oak",
  "ginger",
  "lavender",
  "cinnamon",
  "clove",
  "orange",
  "lemon",
  "apple",
  "raspberry",
  "blackberry",
  "cherry",
  "blueberry",
  "grape",
  "peach",
  "pear",
  "mango",
  "hibiscus",
  "elderberry",

  // Types of Mead
  "traditional",
  "melomel",
  "metheglin",
  "cyser",
  "pyment",
  "braggot",
  "bochet",
  "hydromel",
  "acerglyn",
  "capsicumel",
  "omphacomel",

  // Brewing Processes
  "fermentation",
  "primary",
  "secondary",
  "aging",
  "racking",
  "clarifying",
  "carbonation",
  "bottling",
  "pasteurization",
  "conditioning",
  "flocculation",
  "attenuation",
  "inoculation",
  "pitching",
  "siphoning",
  "sanitizing",
  "boiling",
  "cooling",
  "mashing",
  "sparging",
  "lautering",

  // Brewing Equipment
  "fermenter",
  "carboy",
  "airlock",
  "bung",
  "hydrometer",
  "thermometer",
  "spigot",
  "bucket",
  "syphon",
  "funnel",
  "bottle",
  "keg",
  "air stone",
  "whisk",
  "beaker",
  "measuring cup",
  "scale",
  "mortar",
  "pestle",
  "mash tun",
  "brew kettle",
  "sparge arm",
  "wort chiller",
  "yeast starter",
  "bottle capper",
  "capper",
  "spoon",
  "pipette",
  "graduated cylinder",
  "filter",
  "strainer",

  // Terms and Techniques
  "gravity",
  "original gravity",
  "final gravity",
  "specific gravity",
  "alcohol by volume",
  "abv",
  "pH",
  "brix",
  "acidity",
  "sweetness",
  "mouthfeel",
  "body",
  "aroma",
  "bouquet",
  "clarity",
  "effervescence",
  "oxidation",
  "fermentation temperature",
  "yeast strain",
  "pitch rate",
  "nutrient schedule",
  "refractometer",
  "maturation",
  "lees",
  "must",
  "wort",
  "krausen",
  "wild fermentation",
  "mixed fermentation",
  "back sweetening",
  "dry hopping",
  "cold crashing",
  "aging",
  "temperature control",
  "head space",
  "stirring",
  "oxygenation",

  // Yeast and Bacteria
  "saccharomyces",
  "brettanomyces",
  "lactobacillus",
  "kveik",
  "wild yeast",
  "lager yeast",
  "ale yeast",
  "champagne yeast",
  "baker's yeast",
  "kombucha",
  "kefir",
  "milk kefir",
  "scoby",
  "autolysis",
  "flocculent",
  "low-flocculent",
  "high-flocculent",
  "high attenuation",
  "low attenuation",
  "ester",
  "phenolic",

  // Miscellaneous
  "carbonation level",
  "bottle bomb",
  "yeast cake",
  "sediment",
  "flavor profile",
  "residual sugar",
  "off-flavor",
  "head retention",
  "lacing",
  "clarification",
  "degassing",
  "bottle conditioning",
  "over-carbonated",
  "under-carbonated",
  "meadery",
  "meadmaker",
  "brewmaster",
  "homebrew",
  "brewing journal",
  "recipe",
  "fermentable",
  "mouthfeel",
  "dry",
  "semi-sweet",
  "sweet",
  "sparkling",
  "still",
  "traditional mead",
  "brew day",
  "equipment list",
  "recipe formulation",
  "ingredient sourcing",
  "seasonal flavors",
  "experiment",
  "test batch",
  "custom yeast",
  "high alcohol tolerance",
  "temperature range",
  "brew community",
  "forum",
  "brew club",
];
